### ISSUE TITLE
插件编译报错Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'replugin-plugin-gradle-androidx']

### ISSUE THREAD

**Issue by yingli521** [froyohuang/RePlugin-AndroidX#1]
问题详细描述 Detailed description of the problem
编译demo中的插件报错：
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'replugin-plugin-gradle-androidx']
groovy.lang.MissingPropertyException: No such property: taskManager for class: com.android.build.gradle.AppPlugin
其他：
win7 64
Android Studio 3.6.1
replugin-plugin-gradle-androidx:2.3.3.0

**Comment by froyohuang** [comment]
> 问题详细描述 Detailed description of the problem
> 编译demo中的插件报错：
> Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'replugin-plugin-gradle-androidx']
> groovy.lang.MissingPropertyException: No such property: taskManager for class: com.android.build.gradle.AppPlugin
> 其他：
> win7 64
> Android Studio 3.6.1
> replugin-plugin-gradle-androidx:2.3.3.0

你好，请更新代码，或者手动在项目根目录build.gradle添加如下引用：
        maven{
            url "https://dl.bintray.com/froyo-github/Replugin-AndroidX"
        }

**Comment by ll201lw** [comment]
我这边出现类似问题:Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'replugin-plugin-gradle-androidx' not found.

**Comment by ll201lw** [comment]
问题解决了
